### PR TITLE
feat: add orangepi zero3

### PR DESCRIPTION
**Pull request by meteyou**

### CODE REVIEW

**Review by KwadFan — APPROVED** [review]
LGTM!

**Review by KwadFan — CHANGES_REQUESTED** [review]
After I realized it latly, it is missing our needed FAT32 Boot partition...

**Comment by meteyou** [comment]
i didn't change this option. this should have it as the zero2 image...

**Comment by KwadFan** [comment]
Ok, have to figure out, why it is missing...

**Review by KwadFan — APPROVED** [review]
So, I cant tell what was wrong on my end but it seems the resulting image is correct.

**Pull request merged**
